start python batch_collect_article_desc.py -p 7000
start python batch_collect_article_desc.py -p 7001
start python batch_collect_article_desc.py -p 7002
start python batch_collect_article_desc.py -p 7003
start python batch_collect_article_desc.py -p 7004
start python batch_collect_article_desc.py -p 7005
start python batch_collect_article_desc.py -p 7006
start python batch_collect_article_desc.py -p 7007
start python batch_collect_article_desc.py -p 7008
start python batch_collect_article_desc.py -p 7009
start python batch_collect_article_desc.py -p 7010
start python batch_collect_article_desc.py -p 7011
start python batch_collect_article_desc.py -p 7012
start python batch_collect_article_desc.py -p 7013
start python batch_collect_article_desc.py -p 7014
start python batch_collect_article_desc.py -p 7015
start python batch_collect_article_desc.py -p 7016
start python batch_collect_article_desc.py -p 7017
start python batch_collect_article_desc.py -p 7018
start python batch_collect_article_desc.py -p 7019
