start /B python batch_collect_article_desc.py -p 7100
start /B python batch_collect_article_desc.py -p 7101
start /B python batch_collect_article_desc.py -p 7102
start /B python batch_collect_article_desc.py -p 7103
start /B python batch_collect_article_desc.py -p 7104
start /B python batch_collect_article_desc.py -p 7105
start /B python batch_collect_article_desc.py -p 7106
start /B python batch_collect_article_desc.py -p 7107
start /B python batch_collect_article_desc.py -p 7108
start /B python batch_collect_article_desc.py -p 7109
start /B python batch_collect_article_desc.py -p 7110
start /B python batch_collect_article_desc.py -p 7111
start /B python batch_collect_article_desc.py -p 7112
start /B python batch_collect_article_desc.py -p 7113
start /B python batch_collect_article_desc.py -p 7114
start /B python batch_collect_article_desc.py -p 7115
start /B python batch_collect_article_desc.py -p 7116
start /B python batch_collect_article_desc.py -p 7117
start /B python batch_collect_article_desc.py -p 7118
start /B python batch_collect_article_desc.py -p 7119
start /B python batch_collect_article_desc.py -p 7120
start /B python batch_collect_article_desc.py -p 7121
start /B python batch_collect_article_desc.py -p 7122
start /B python batch_collect_article_desc.py -p 7123
start /B python batch_collect_article_desc.py -p 7124
start /B python batch_collect_article_desc.py -p 7125
start /B python batch_collect_article_desc.py -p 7126
start /B python batch_collect_article_desc.py -p 7127
start /B python batch_collect_article_desc.py -p 7128
start /B python batch_collect_article_desc.py -p 7129
start /B python batch_collect_article_desc.py -p 7130
start /B python batch_collect_article_desc.py -p 7131
start /B python batch_collect_article_desc.py -p 7132
start /B python batch_collect_article_desc.py -p 7133
start /B python batch_collect_article_desc.py -p 7134
start /B python batch_collect_article_desc.py -p 7135
start /B python batch_collect_article_desc.py -p 7136
start /B python batch_collect_article_desc.py -p 7137
start /B python batch_collect_article_desc.py -p 7138
start /B python batch_collect_article_desc.py -p 7139
start /B python batch_collect_article_desc.py -p 7140
start /B python batch_collect_article_desc.py -p 7141
start /B python batch_collect_article_desc.py -p 7142
start /B python batch_collect_article_desc.py -p 7143
start /B python batch_collect_article_desc.py -p 7144
start /B python batch_collect_article_desc.py -p 7145
start /B python batch_collect_article_desc.py -p 7146
start /B python batch_collect_article_desc.py -p 7147
start /B python batch_collect_article_desc.py -p 7148
start /B python batch_collect_article_desc.py -p 7149
start /B python batch_collect_article_desc.py -p 7150
start /B python batch_collect_article_desc.py -p 7151
start /B python batch_collect_article_desc.py -p 7152
start /B python batch_collect_article_desc.py -p 7153
start /B python batch_collect_article_desc.py -p 7154
start /B python batch_collect_article_desc.py -p 7155
start /B python batch_collect_article_desc.py -p 7156
start /B python batch_collect_article_desc.py -p 7157
start /B python batch_collect_article_desc.py -p 7158
start /B python batch_collect_article_desc.py -p 7159
start /B python batch_collect_article_desc.py -p 7160
start /B python batch_collect_article_desc.py -p 7161
start /B python batch_collect_article_desc.py -p 7162
start /B python batch_collect_article_desc.py -p 7163
start /B python batch_collect_article_desc.py -p 7164
start /B python batch_collect_article_desc.py -p 7165
start /B python batch_collect_article_desc.py -p 7166
start /B python batch_collect_article_desc.py -p 7167
start /B python batch_collect_article_desc.py -p 7168
start /B python batch_collect_article_desc.py -p 7169
start /B python batch_collect_article_desc.py -p 7170
start /B python batch_collect_article_desc.py -p 7171
start /B python batch_collect_article_desc.py -p 7172
start /B python batch_collect_article_desc.py -p 7173
start /B python batch_collect_article_desc.py -p 7174
start /B python batch_collect_article_desc.py -p 7175
start /B python batch_collect_article_desc.py -p 7176
start /B python batch_collect_article_desc.py -p 7177
start /B python batch_collect_article_desc.py -p 7178
start /B python batch_collect_article_desc.py -p 7179
start /B python batch_collect_article_desc.py -p 7180
start /B python batch_collect_article_desc.py -p 7181
start /B python batch_collect_article_desc.py -p 7182
start /B python batch_collect_article_desc.py -p 7183
start /B python batch_collect_article_desc.py -p 7184
start /B python batch_collect_article_desc.py -p 7185
start /B python batch_collect_article_desc.py -p 7186
start /B python batch_collect_article_desc.py -p 7187
start /B python batch_collect_article_desc.py -p 7188
start /B python batch_collect_article_desc.py -p 7189
start /B python batch_collect_article_desc.py -p 7190
start /B python batch_collect_article_desc.py -p 7191
start /B python batch_collect_article_desc.py -p 7192
start /B python batch_collect_article_desc.py -p 7193
start /B python batch_collect_article_desc.py -p 7194
start /B python batch_collect_article_desc.py -p 7195
start /B python batch_collect_article_desc.py -p 7196
start /B python batch_collect_article_desc.py -p 7197
start /B python batch_collect_article_desc.py -p 7198
start /B python batch_collect_article_desc.py -p 7199
