nohup python3 batch_collect_article_desc.py -p 7100 &
nohup python3 batch_collect_article_desc.py -p 7101 &
nohup python3 batch_collect_article_desc.py -p 7102 &
nohup python3 batch_collect_article_desc.py -p 7103 &
nohup python3 batch_collect_article_desc.py -p 7104 &
nohup python3 batch_collect_article_desc.py -p 7105 &
nohup python3 batch_collect_article_desc.py -p 7106 &
nohup python3 batch_collect_article_desc.py -p 7107 &
nohup python3 batch_collect_article_desc.py -p 7108 &
nohup python3 batch_collect_article_desc.py -p 7109 &
nohup python3 batch_collect_article_desc.py -p 7110 &
nohup python3 batch_collect_article_desc.py -p 7111 &
nohup python3 batch_collect_article_desc.py -p 7112 &
nohup python3 batch_collect_article_desc.py -p 7113 &
nohup python3 batch_collect_article_desc.py -p 7114 &
nohup python3 batch_collect_article_desc.py -p 7115 &
nohup python3 batch_collect_article_desc.py -p 7116 &
nohup python3 batch_collect_article_desc.py -p 7117 &
nohup python3 batch_collect_article_desc.py -p 7118 &
nohup python3 batch_collect_article_desc.py -p 7119 &
nohup python3 batch_collect_article_desc.py -p 7120 &
nohup python3 batch_collect_article_desc.py -p 7121 &
nohup python3 batch_collect_article_desc.py -p 7122 &
nohup python3 batch_collect_article_desc.py -p 7123 &
nohup python3 batch_collect_article_desc.py -p 7124 &
nohup python3 batch_collect_article_desc.py -p 7125 &
nohup python3 batch_collect_article_desc.py -p 7126 &
nohup python3 batch_collect_article_desc.py -p 7127 &
nohup python3 batch_collect_article_desc.py -p 7128 &
nohup python3 batch_collect_article_desc.py -p 7129 &
nohup python3 batch_collect_article_desc.py -p 7130 &
nohup python3 batch_collect_article_desc.py -p 7131 &
nohup python3 batch_collect_article_desc.py -p 7132 &
nohup python3 batch_collect_article_desc.py -p 7133 &
nohup python3 batch_collect_article_desc.py -p 7134 &
nohup python3 batch_collect_article_desc.py -p 7135 &
nohup python3 batch_collect_article_desc.py -p 7136 &
nohup python3 batch_collect_article_desc.py -p 7137 &
nohup python3 batch_collect_article_desc.py -p 7138 &
nohup python3 batch_collect_article_desc.py -p 7139 &
nohup python3 batch_collect_article_desc.py -p 7140 &
nohup python3 batch_collect_article_desc.py -p 7141 &
nohup python3 batch_collect_article_desc.py -p 7142 &
nohup python3 batch_collect_article_desc.py -p 7143 &
nohup python3 batch_collect_article_desc.py -p 7144 &
nohup python3 batch_collect_article_desc.py -p 7145 &
nohup python3 batch_collect_article_desc.py -p 7146 &
nohup python3 batch_collect_article_desc.py -p 7147 &
nohup python3 batch_collect_article_desc.py -p 7148 &
nohup python3 batch_collect_article_desc.py -p 7149 &
nohup python3 batch_collect_article_desc.py -p 7150 &
nohup python3 batch_collect_article_desc.py -p 7151 &
nohup python3 batch_collect_article_desc.py -p 7152 &
nohup python3 batch_collect_article_desc.py -p 7153 &
nohup python3 batch_collect_article_desc.py -p 7154 &
nohup python3 batch_collect_article_desc.py -p 7155 &
nohup python3 batch_collect_article_desc.py -p 7156 &
nohup python3 batch_collect_article_desc.py -p 7157 &
nohup python3 batch_collect_article_desc.py -p 7158 &
nohup python3 batch_collect_article_desc.py -p 7159 &
nohup python3 batch_collect_article_desc.py -p 7160 &
nohup python3 batch_collect_article_desc.py -p 7161 &
nohup python3 batch_collect_article_desc.py -p 7162 &
nohup python3 batch_collect_article_desc.py -p 7163 &
nohup python3 batch_collect_article_desc.py -p 7164 &
nohup python3 batch_collect_article_desc.py -p 7165 &
nohup python3 batch_collect_article_desc.py -p 7166 &
nohup python3 batch_collect_article_desc.py -p 7167 &
nohup python3 batch_collect_article_desc.py -p 7168 &
nohup python3 batch_collect_article_desc.py -p 7169 &
nohup python3 batch_collect_article_desc.py -p 7170 &
nohup python3 batch_collect_article_desc.py -p 7171 &
nohup python3 batch_collect_article_desc.py -p 7172 &
nohup python3 batch_collect_article_desc.py -p 7173 &
nohup python3 batch_collect_article_desc.py -p 7174 &
nohup python3 batch_collect_article_desc.py -p 7175 &
nohup python3 batch_collect_article_desc.py -p 7176 &
nohup python3 batch_collect_article_desc.py -p 7177 &
nohup python3 batch_collect_article_desc.py -p 7178 &
nohup python3 batch_collect_article_desc.py -p 7179 &
nohup python3 batch_collect_article_desc.py -p 7180 &
nohup python3 batch_collect_article_desc.py -p 7181 &
nohup python3 batch_collect_article_desc.py -p 7182 &
nohup python3 batch_collect_article_desc.py -p 7183 &
nohup python3 batch_collect_article_desc.py -p 7184 &
nohup python3 batch_collect_article_desc.py -p 7185 &
nohup python3 batch_collect_article_desc.py -p 7186 &
nohup python3 batch_collect_article_desc.py -p 7187 &
nohup python3 batch_collect_article_desc.py -p 7188 &
nohup python3 batch_collect_article_desc.py -p 7189 &
nohup python3 batch_collect_article_desc.py -p 7190 &
nohup python3 batch_collect_article_desc.py -p 7191 &
nohup python3 batch_collect_article_desc.py -p 7192 &
nohup python3 batch_collect_article_desc.py -p 7193 &
nohup python3 batch_collect_article_desc.py -p 7194 &
nohup python3 batch_collect_article_desc.py -p 7195 &
nohup python3 batch_collect_article_desc.py -p 7196 &
nohup python3 batch_collect_article_desc.py -p 7197 &
nohup python3 batch_collect_article_desc.py -p 7198 &
nohup python3 batch_collect_article_desc.py -p 7199 &
