nohup python3 batch_collect_article_desc.py -p 7000 &
nohup python3 batch_collect_article_desc.py -p 7001 &
nohup python3 batch_collect_article_desc.py -p 7002 &
nohup python3 batch_collect_article_desc.py -p 7003 &
nohup python3 batch_collect_article_desc.py -p 7004 &
nohup python3 batch_collect_article_desc.py -p 7005 &
nohup python3 batch_collect_article_desc.py -p 7006 &
nohup python3 batch_collect_article_desc.py -p 7007 &
nohup python3 batch_collect_article_desc.py -p 7008 &
nohup python3 batch_collect_article_desc.py -p 7009 &
nohup python3 batch_collect_article_desc.py -p 7010 &
nohup python3 batch_collect_article_desc.py -p 7011 &
nohup python3 batch_collect_article_desc.py -p 7012 &
nohup python3 batch_collect_article_desc.py -p 7013 &
nohup python3 batch_collect_article_desc.py -p 7014 &
nohup python3 batch_collect_article_desc.py -p 7015 &
nohup python3 batch_collect_article_desc.py -p 7016 &
nohup python3 batch_collect_article_desc.py -p 7017 &
nohup python3 batch_collect_article_desc.py -p 7018 &
nohup python3 batch_collect_article_desc.py -p 7019 &
nohup python3 batch_collect_article_desc.py -p 7020 &
nohup python3 batch_collect_article_desc.py -p 7021 &
nohup python3 batch_collect_article_desc.py -p 7022 &
nohup python3 batch_collect_article_desc.py -p 7023 &
nohup python3 batch_collect_article_desc.py -p 7024 &
nohup python3 batch_collect_article_desc.py -p 7025 &
nohup python3 batch_collect_article_desc.py -p 7026 &
nohup python3 batch_collect_article_desc.py -p 7027 &
nohup python3 batch_collect_article_desc.py -p 7028 &
nohup python3 batch_collect_article_desc.py -p 7029 &
nohup python3 batch_collect_article_desc.py -p 7030 &
nohup python3 batch_collect_article_desc.py -p 7031 &
nohup python3 batch_collect_article_desc.py -p 7032 &
nohup python3 batch_collect_article_desc.py -p 7033 &
nohup python3 batch_collect_article_desc.py -p 7034 &
nohup python3 batch_collect_article_desc.py -p 7035 &
nohup python3 batch_collect_article_desc.py -p 7036 &
nohup python3 batch_collect_article_desc.py -p 7037 &
nohup python3 batch_collect_article_desc.py -p 7038 &
nohup python3 batch_collect_article_desc.py -p 7039 &
nohup python3 batch_collect_article_desc.py -p 7040 &
nohup python3 batch_collect_article_desc.py -p 7041 &
nohup python3 batch_collect_article_desc.py -p 7042 &
nohup python3 batch_collect_article_desc.py -p 7043 &
nohup python3 batch_collect_article_desc.py -p 7044 &
nohup python3 batch_collect_article_desc.py -p 7045 &
nohup python3 batch_collect_article_desc.py -p 7046 &
nohup python3 batch_collect_article_desc.py -p 7047 &
nohup python3 batch_collect_article_desc.py -p 7048 &
nohup python3 batch_collect_article_desc.py -p 7049 &
nohup python3 batch_collect_article_desc.py -p 7050 &
nohup python3 batch_collect_article_desc.py -p 7051 &
nohup python3 batch_collect_article_desc.py -p 7052 &
nohup python3 batch_collect_article_desc.py -p 7053 &
nohup python3 batch_collect_article_desc.py -p 7054 &
nohup python3 batch_collect_article_desc.py -p 7055 &
nohup python3 batch_collect_article_desc.py -p 7056 &
nohup python3 batch_collect_article_desc.py -p 7057 &
nohup python3 batch_collect_article_desc.py -p 7058 &
nohup python3 batch_collect_article_desc.py -p 7059 &
nohup python3 batch_collect_article_desc.py -p 7060 &
nohup python3 batch_collect_article_desc.py -p 7061 &
nohup python3 batch_collect_article_desc.py -p 7062 &
nohup python3 batch_collect_article_desc.py -p 7063 &
nohup python3 batch_collect_article_desc.py -p 7064 &
nohup python3 batch_collect_article_desc.py -p 7065 &
nohup python3 batch_collect_article_desc.py -p 7066 &
nohup python3 batch_collect_article_desc.py -p 7067 &
nohup python3 batch_collect_article_desc.py -p 7068 &
nohup python3 batch_collect_article_desc.py -p 7069 &
nohup python3 batch_collect_article_desc.py -p 7070 &
nohup python3 batch_collect_article_desc.py -p 7071 &
nohup python3 batch_collect_article_desc.py -p 7072 &
nohup python3 batch_collect_article_desc.py -p 7073 &
nohup python3 batch_collect_article_desc.py -p 7074 &
nohup python3 batch_collect_article_desc.py -p 7075 &
nohup python3 batch_collect_article_desc.py -p 7076 &
nohup python3 batch_collect_article_desc.py -p 7077 &
nohup python3 batch_collect_article_desc.py -p 7078 &
nohup python3 batch_collect_article_desc.py -p 7079 &
nohup python3 batch_collect_article_desc.py -p 7080 &
nohup python3 batch_collect_article_desc.py -p 7081 &
nohup python3 batch_collect_article_desc.py -p 7082 &
nohup python3 batch_collect_article_desc.py -p 7083 &
nohup python3 batch_collect_article_desc.py -p 7084 &
nohup python3 batch_collect_article_desc.py -p 7085 &
nohup python3 batch_collect_article_desc.py -p 7086 &
nohup python3 batch_collect_article_desc.py -p 7087 &
nohup python3 batch_collect_article_desc.py -p 7088 &
nohup python3 batch_collect_article_desc.py -p 7089 &
nohup python3 batch_collect_article_desc.py -p 7090 &
nohup python3 batch_collect_article_desc.py -p 7091 &
nohup python3 batch_collect_article_desc.py -p 7092 &
nohup python3 batch_collect_article_desc.py -p 7093 &
nohup python3 batch_collect_article_desc.py -p 7094 &
nohup python3 batch_collect_article_desc.py -p 7095 &
nohup python3 batch_collect_article_desc.py -p 7096 &
nohup python3 batch_collect_article_desc.py -p 7097 &
nohup python3 batch_collect_article_desc.py -p 7098 &
nohup python3 batch_collect_article_desc.py -p 7099 &
